apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
  namespace: qq2
spec:
  containers:
  - image: nginx
    name: pod
    resources: {}
    volumeMounts:
    - mountPath: /data
      name: data-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: podpvc
