apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: qq2
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - mountPath: "/data"
        name: mydata
  volumes:
    - name: mydata
      persistentVolumeClaim:
        claimName: pvc