apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podpvc
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /data
      name: test-app
  volumes:
    - name: test-app
      persistentVolumeClaim:
        claimName: podpvc
