apiVersion: v1
data:
  PGADMIN_LISTEN_PORT: "8080"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: pgadmin
  namespace: postgres
---
apiVersion: v1
data:
  PGADMIN_DEFAULT_EMAIL: bm9vcmFpbWFuejA2QGdtYWlsLmNvbQ==
  PGADMIN_DEFAULT_PASSWORD: YWltYW4=
kind: Secret
metadata:
  creationTimestamp: null
  name: pgadmin
  namespace: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pgadmin
  name: pgadmin
  namespace: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pgadmin
    spec:
      containers:
      - image: elestio/pgadmin
        name: pgadmin
        ports:
        - containerPort: 8080
        resources: {}
        envFrom:
        - configMapRef:
            name: pgadmin
        - secretRef:
            name: pgadmin
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pgadmin
  name: pgadmin
  namespace: postgres
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: pgadmin
