     - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: postgres-volume
              subPath: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secret
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secret
                  key: POSTGRES_DB

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      protocol: TCP
  selector:
    app: postgres

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv002
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  hostPath:
    path: /
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node01
---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
data:
  POSTGRES_USER: YWltYW4=
  POSTGRES_PASSWORD: YWJjMTIz
  POSTGRES_DB: cG9zdGdyZXM=
  ADMIN_PASSWORD: YWJjMTIz