apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: qq2
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
      - mountPath: "/data"
        readOnly: true
        name: podpvc
  volumes:
    - name: podpvc
      persistentVolumeClaim:
        claimName: podpvc