apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: cloud-app01
spec:
  # 3 Pods should exist at all times.
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: nginx
    spec:
      containers:
      - name: nginx
        # Run this image
        image: nginx:1.23.3-alpine
        ports:
        - containerPort: 80