apiVersion: v1
kind: Secret
metadata:
  name: credentials
data:
  username: YWltYW4tYWlzYQ==
  password: YWJjMTIz

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: q5
data:
  content: "aiman"

---
apiVersion: v1
kind: Pod
metadata:
  name: apache
spec:
  containers:
    - name: apache
      image: httpd
      env:
        - name: CONTENT
          valueFrom:
            configMapKeyRef:
              name: q5
              key: content
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: credentials
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: password
