apiVersion: v1
kind: ConfigMap
metadata:
  name: q5
  namespace: default
data:
  content: "content"

---

apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: secret
data:
  username: YWRtaW4=
  password: YWRtaW4=

--- 

apiVersion: v1
kind: Pod
metadata:
  name: apache
  namespace: default
spec:
  containers:
  - name: apache-container
    image: httpd
    env:
    - name: CONTENT
      valueFrom:
        configMapKeyRef:
          name: q5
          key: content
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: credentials
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: credentials
          key: password
