apiVersion: v1
kind: ConfigMap
metadata:
  name: q5
  namespace: qq3
data:
  content: "Berjaya"

apiVersion: v1
kind: Pod
metadata:
  name: apache
  namespace: qq3
spec:
  containers:
  - name: apache
    image: httpd:latest
    env:
    - name: CONTENT
      valueFrom:
        configMapKeyRef:
          name: q5
          key: content
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: credentials
          key: USER
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: credentials
          key: PASSWORD