apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: apache
  name: apache
spec:
  containers:
  - args:
    - client
    image: httpd
    name: apache
    env:
    - name: CONTENT
      valueFrom:
        configMapKeyRef:
          name: q5
          key: content
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: credentials
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: credentials
          key: password
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
