apiVersion: v1
kind: ConfigMap
metadata:
  name: q5
data:
  content: "test"

---

apiVersion: v1
kind: Secret
metadata:
  name: credentials
data:
  username: "YWRpYmFrbm9vcg=="
  password: "YWRpYjEyMzQ="


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: apache:httpd
        ports:
        - containerPort: 8080
        env:
        - name: CONTENT
          valueFrom:
            configMapKeyRef:
              name: q5
              key: content
        - name: USERNAME
          valueFrom:
           secretKeyRef:
              name: credentials
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: password
