apiVersion: v1
kind: ConfigMap
metadata:
  name: q5
data:
  CONTENT: test
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials
data:
  USERNAME: YWRtaW4K
  USERNAME: YWRtaW4K
---
apiVersion: v1
kind: Pod
metadata:
  name: apache
spec:
  containers:
  - name: apache
    image: httpd
    ports:
    - containerPort: 80
    env:
      - name: CONTENT
        valueFrom:
          configMapKeyRef:
            name: q5
            key: CONTENT
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: credentials
            key: USERNAME
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: credentials
            key: PASSWORD