apiVersion: v1
kind: Service
metadata:
  name: cloud-app-svc
spec:
  type: NodePort
  selector:
    app: cloud-app01
  ports:
    - protocol: TCP
      port: 80
      targetPort: cloud-app01

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-app01
  labels:
    app: cloud-app01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-app01
  template:
    metadata:
      labels:
        app: cloud-app01
    spec:
      containers:
      - name: cloud-app01
        image: nginx:1.23.3-alpine
        ports:
        - containerPort: 80
          name: cloud-app01