apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  storageClassName: gp
  capacity:
    storage: 21Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
      path: /mnt/data
  persistentVolumeReclaimPolicy: Retain

  ---

  apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp