apiVersion: v1
kind: Pod
metadata:
  name: limit
spec:
  containers:
    - name: app
      image: redis
      resources:
        requests:
          memory: "500Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1M"
