apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: limit
  name: limit
  namespace: qq3
spec:
  containers:
  - image: redis
    name: limit
    resources:
      requests:
        cpu: "0.5"
        memory: "500Mi"
      limits:
        cpu: "1"
        memory: "1Gi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
