apiVersion: v1
kind: Pod
metadata:
  name: limit
spec:
  containers:
  - name: redis
    image: redis
    resources:
      requests:
        memory: "500Mi"
        cpu: "0.5"
      limits:
        memory: "1Gi"
        cpu: "1"
    ports:
    - containerPort: 6379
