apiVersion: v1
kind: Pod
metadata:
  name: limit
  namespace: qq3
spec:
  containers:
  - name: redis
    image: redis:latest
    resources:
      requests:
        cpu: "0.5"
        memory: "500Mi"
      limits:
        cpu: "1"
        memory: "1Gi"