apiVersion: apps/v1
kind: Deployment
metadata:
  name: web 
  namespace: ca1
  labels:
    app: web 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web 
  template:
    metadata:
      labels:
        app: web 
    spec:
      containers:
      - name: web 
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: ca1
spec:
  selector:
    app: web 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-host-fqdn 
  namespace: ca1
data:
  host: 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web 
  namespace: ca1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /path
spec:
  ingressClassName: nginx-example
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-svc 
            port:
              number: 80