apiVersion: v1
kind: Service
metadata:
  name: app01-svc
spec:
  type: NodePort
  selector:
    app: app01
  ports:
    - protocol: TCP
      port: 80
      targetPort: app01

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01
  labels:
    app: app01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app01
  template:
    metadata:
      labels:
        app: app01
    spec:
      containers:
      - name: app01
        image: nginx:latest
        ports:
        - containerPort: 80
          name: app01