apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app01
  template:
    metadata:
      labels:
        app: app01
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: app01-svc
  namespace: prod
spec:
  selector:
    app: app01apiVersion: v1
kind: Service
metadata:
  name: app01-svc
  namespace: prod
spec:
  selector:
    app: app01
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 80001  
  type: NodePort
