apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /data
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
    readinessProbe  : 
      httpGet:
        path: /data
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
