apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: lab-deployment
  name: lab-deployment
  namespace: qq2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lab-deployment
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources: {}
status: {}
