apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-deployment
  namespace: qq2
  labels:
    app: lab-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-app
  template:
    metadata:
      labels:
        app: lab-app
    spec:
      containers:
      - name: lab-container
        image: nginx:latest
        ports:
        - containerPort: 80